### ISSUE TITLE
Not avoiding an unpleasant way

### ISSUE THREAD

**Issue by utack** [poutnikl/Brouter-profiles#10]
Hi,
sorry to start another discussion about profiles here, but I found something that might be interesting to look at again
Using the Trekking-fast profile on this example route:

http://brouter.de/brouter-web/#zoom=15&lat=50.91642&lon=14.15751&layer=OpenStreetMap&lonlats=14.14582,50.917402|14.16966,50.911868&nogos=&alternativeidx=0&format=geojson

A long part of the way is "surface=gravel"
Gravel are really large stones, according to OSM Wiki. It is impossible to go over with a racing bike, and on that part of the way even with a mountainbike you can do no more than 8km/h. 
(yes, it is absolutely idiotic that it is part of a cycleroute, but I did not design that route and that is not worth discussing here)
We definitely want to avoid that part and go over the road with asphalt here
How can it be fixed to do so?

Thank you

PS: Let me know if you'd prefer discussions like this on the brouter google group

**Comment by poutnikl** [comment]
Talking at Github is fine, while it discuss my profiles or Github wiki content for particular details.
If it may be interesting for broad Brouter audience, Brouter group can be considered as well..

I would separate the routing case topic to points:
*  **Wrong mapping to fix routing, wrong routing to fix mapping**  
   Mapping should reflect the way physical conditions, status and marking. Routing algorithms must  be based on what the map vector data contains, not what is in the terrain. It is not good idea to bend routing algorithm for cases the mapping is incorrect. 

* **Suggestion** : I recommend to fix the [mapping] as mentioned below.(https://www.openstreetmap.org)  \( BRouter rd5 file have 7-10 days update frequency \), and to temporarily use the [Brouter nogo points](https://github.com/poutnikl/Brouter-profiles/wiki/Glossary#n).

*  **Used mapping** 
   Even if there is marked surface=gravel, it is marked not only as international cycleroute, but even as highway=cycleway, with access bicycle=designated. So the routing can legitimately suppose it is usable for bicycle travelling.   
Default Brouter profiles even take all highway=cycleway as perfect. My profiles are more hesitating ( but not avoiding ), seeing surface=gravel. 
  
*  **surface\=gravel and the case fixing of mapping** - gravel is often used, more or less correctly for quite a range of surfaces, from loose gravel through [water-bound/macadam](https://wiki.openstreetmap.org/wiki/Talk:Key:surface#gravel_.2F_water-bound_.2F_macadam) to compacted surface ( where surface=compacted should be used). I suggest  possible mapping actions, based on the terrain survey. All 4 of them are evaluated in the profile"

     * reconsider the proper surface=* tag, but what i understands there is loose gravel, so surface=gravel should be correct
     * consider usage [tracktype=* tag](https://wiki.openstreetmap.org/wiki/Key:tracktype)
     * consider [smoothness=* tag ](https://wiki.openstreetmap.org/wiki/Key:smoothness)
     * consider [mtb:scale=* tag ](https://wiki.openstreetmap.org/wiki/Key:mtb:scale)

* **Traveling gravel** : I often go through gravel roads on my trekking bike. They are seldom like really loose gravel. They are often more or lass flattened by the traffic or explicitly by the roler , or integrated with the soil bases into tracktype=grade2 or grade3.  So they fit to some range of applicable smoothness=* and tracktype=* values.

*  **Trekking-fast** - the profile is NOT intended for racing/fast road bikes.  
    It is trekking profile just shifted little toward paved roads. Use original Fastbike profile, or change the MTB_factor from -0.5 ( Trekking-fast) to -1.5 - -2.0 ( Fastbike-like).   
It would not avoid gravel, but would assign it very low priority.

**Comment by poutnikl** [comment]
about the placing, it could be as well as placing discussion to the group, while raising the issue with short summary to GH issue page, cross-linking them. The issue page has advantage it is harder to be forgotten.

**Comment by utack** [comment]
Right i see how it makes sense..probably a rare case that an official cycleway is that garbage
