### ISSUE TITLE
Missing route types used in Budapest

### ISSUE THREAD

**Issue by ghost** [poutnikl/Brouter-profiles#13]
Hello!

I discovered that in Budapest there are a few more tags used for bicycle relevant roads than in your profiles.
For example:
cycleway=lane
cycleway:right=lane
cycleway=shared_lane

Is it possible to include these too in the profile, or the brouter segments does not contains these by default?
If possible then I can collect them for you, or maybe I can include theese in the profiles if you tell me how to do. :)

Best,
Gabor

**Comment by poutnikl** [comment]
There is the variable
`assign hascycleway = 
 not  and ( or cycleway= cycleway=no|none ) and ( or cycleway:left= cycleway:left=no ) ( or cycleway:right= cycleway:right=no )`

So various values for cycleway[:[left|right]] other then  "no" or "" are implicitly considered.

Note that my profiles are not primarily aimed for the city traffic, even if well usable. You may want to consider checking a quite new profile in development, dedicated to the city/street traffic, considering many complex city specific conditions. I am going to implement some of his features later as well.

[Jacob's streetbike profile](https://raw.githubusercontent.com/utack/utack_brouter_data/master/streetbike_touring.brf) at repository [utack_brouter_data](https://github.com/utack/utack_brouter_data)

**Comment by utack** [comment]
thanks for mentioning it @poutnikl 
Something to note about this:
My profile assumes cycleway:right and cycleway:left are oneway, this is against the OSM wiki, but how it is mostly (as in almost always) used in Germany  
What should be additionally included in my profile is oneway street cycleways (opposite_lane and opposite_track)
Your profile is working just as well, when people tag strictly according to OSM wiki

**Comment by poutnikl** [comment]
Then the profiles can complement each other, @utack  :-) One or the other will work well.
What about implementing Germany switch for people in regions following the wiki ?

**Comment by utack** [comment]
I was wrong, the wiki recommends
> It should then be assumed that cycle traffic is allowed to flow in the customary direction for traffic on that side of the road  
  
The exception is cycleway:left/right:oneway=no, which is currently not possible to check for in BRouter, see [here](https://github.com/utack/utack_brouter_data/blob/master/streetbike_touring.brf#L99)
Example:
https://www.openstreetmap.org/way/175725446
Once the new data format is included, we should be able to check for this as well
On my personal "todo" list is to re-structure the cycleway logic similar to the oneway logic, by looking at traffic flow directions. It should bring more logic to the checks

**Comment by poutnikl** [comment]
for @dnbstyle , just for completeness, as you probably know, cycleway=*  tag is a feature tag of the main highway=* road. It is not an independent way in OSM context, in contrary to highway=cycleway, even if physically it can be. The routing does not follow cycleway=, but the major highway. Neither the routing geometrically distinguishes the main road and the side cycleway, aside of cycleway:left=* or cycleway:right=*.

The biker is supposed to visually recognize the present cycleway and use it, if desired or required.
The profiles grant the better priorities to roads that have a side cycleway.

**Comment by ghost** [comment]
Thank you for your kind help! I didn't know that this is not a distinct separate tag. Then I will check the streetbike profile too and tweak either to fit my needs. :)

**Comment by andrew-james-heard** [comment]
May I ask what is the advantage or design goal of the streetbike profile
compared to fastbike? I mostly use small roads, tertiaries and velomobile.
------
cheers Andrew

**Comment by utack** [comment]
@andrew-james-heard it is a little different from "fastbike" (if you are speaking about the BRouter default fastbike)

Two things I wanted to do better

- Treat all ways equally. One example: If we encounter a highway=unclassified and surface=cobblestone, we look at the surface=cobblestone, while the "fastbike" profile just assigns fixed costfactor 1.1  
  
- Proper evaluation for oneways and proper determination if there is a cycleway in the direction we are driving

One thing that are just preference for my driving style:

- There is still traffic cost. I am not a race-biking person, while surface is important for my bike with no suspension and thin wheels, I still prefer a mostly-pleasant way with something like compacted fine gravel over a really busy highway with asphalt, or the bike-way with slightly uneven "paving stones" over the street next to it  
- That also means we can go very short ways that are really nasty, like "surface=grass", if it means we can avoid a lot of busy highway with it  
  
And things it does worse:

- The profile is pretty "fixed" purpose, while the fastbike profile has countless switches to configure for your own wishes
- It does not generate turn instructions
  
Hope this helps

**Comment by andrew-james-heard** [comment]
Thanks for the details. Sounds to me like a good replacement for BRouter
fastbike then.
------
cheers Andrew

**Comment by utack** [comment]
Let me know if it does some nonsense in your area please

**Comment by poutnikl** [comment]
@andrew-james-heard  : Have you tried [fastbike-lowtraffic-tertiaries](https://raw.githubusercontent.com/poutnikl/Brouter-profiles/master/BikeProfiles/Fastbike-lowtraffic-tertiaries.brf) - a Fastbike-lowtraffic derivative ? (Trekking-tertiaries is different profile and is based on my template ). 

Josef Zajdlik on Locus forum likes it very much for a road bike. It reportedly offered exactly the same routes he would choose for multiple testing routes he personally knows. He would even replace Fastbike by this.

**Comment by utack** [comment]
@andrew-james-heard i have yet to do left hand traffic support for the cycle way detection, in case you need that

**Comment by andrew-james-heard** [comment]
Thanks but no rush. We are cycle touring in Italy for 9 weeks, so won't
check your new profile until return to Tasmania .
------
cheers Andrew
