### ISSUE TITLE
sidewalk

### ISSUE THREAD

**Issue by tobydickenson** [poutnikl/Brouter-profiles#17]
I use the Walking profile in mixed suburban/rural environments. It generally works wonderfully, but occasionally I see silly routing which I am attributing to the handling of sidewalks.

I am using this to document some experimental changes to the walking profile to better handle sidewalks

Pull request to following if this all works out

**Comment by poutnikl** [comment]
Note the Brouter-profiles project serves just as the depository of end profiles, generated by a script from respective templates. Each template had its own project and all development and eventual pull requests is done there. For foot profiles, it is the Hiking-Poutnik project.
