### ISSUE TITLE
Missing Commuting profile

### ISSUE THREAD

**Issue by pedrorolo** [poutnikl/Brouter-profiles#19]
Hi! I am bafled by the lack of a commuting profile both on your collection and on the brouter standard profiles. I understand that one can cook one as per your instructions, though, why not offering one right away?

**Comment by poutnikl** [comment]
Hi. The question is, if it is needed, as it exists under different names.

The "Commuting profile" is a vaque term, as some prefer pleasant, quiet and safe, even if slow routes, while others prefer fast routes, even if noisy, less safe with traffic.

For the former, one can choose the standard or my trekking profile with or without ignoring cycleroutes.

For the latter, standard fastbike (low traffic), or my trekking-fast or fastbike-lowtraffic-tertiaries.

Be aware my profiles are near all based on my trekking profile template
and as such, they are rather "bent trekking profiles" toward chosen bias.
Thus bending us not specific to commuting, so one can choose various bending toward main, middle and small roads.

The question also is, if one needs any routing for regular commuting.

Last, but not least, definitely try Jacob's city/street profile. (link on readme page of my Brouter-profiles repository.
It was much more originally taylored wrt to commuting in urban-like areas
and its logic for sideways is I guess more complete.

**Comment by pedrorolo** [comment]
Thank you very much for your answer. I will try Jacob's.
