### ISSUE TITLE
Ignore bicycle=use_sidepath ways

### ISSUE THREAD

**Issue by UgnilJoZ** [poutnikl/Brouter-profiles#27]
Brouter's trekking bicycle profile sends me ~20meters on a primary highway which is tagged with `bicycle=use_sidepath`, because it makes a shorter route. In reality this shortcut cannot be taken by a bicycle.

I would expect to be never sent on highways with this tag.

**Comment by poutnikl** [comment]
Which profile particularly ? As "trekking" profile is a part of [BRouter package](https://github.com/abrensch/brouter), not mine.

Approach is question of point of view. If sidepath took significanly longer than pushing a bike I would prefer to bt sent on primary one, even if I had to push the bike. 

Another  case would be if the sidepath was not passable.

**Comment by UgnilJoZ** [comment]
Sorry, I opened it in the wrong repository then.

The critical point would be that cycling is forbidden on the main way, and only allowed on the sidepaths.

**Comment by poutnikl** [comment]
I got that, but one must consider hard versus soft way of no-gos. Total hard forbiding can have severe and not always foreseen consequence. Fallback to pushing  for limited distance is in some cases acceptable alternative way of motion.
