### ISSUE TITLE
Include oneway fixes from https://github.com/abrensch/brouter/issues/51

### ISSUE THREAD

**Issue by utack** [poutnikl/Brouter-profiles#7]
The comment in
https://github.com/abrensch/brouter/issues/51#issuecomment-247367551
explains how to make routing aware of oneway:bicycle=yes
Copy+paste into your trekking profiles worked for me, it should probably be included in all profilkes

**Comment by poutnikl** [comment]
Fixed in profiles v2.5.4. Thanks for getting know.

**Comment by utack** [comment]
That was fast, thanks
